[package]
name     = "glaze-refactor"
version  = "0.3.0"
authors  = ["Davide Pizzolotto <davide.pizzolotto@gmail.com>"]
edition  = "2021"
license  = "MIT"

[dependencies]
ash = "0.37"
log = "0.4"

[target.'cfg(target_os="windows")'.dependencies]
windows = { version = "0.51" }

[features]
