use crate::graphics::format::ImageFormat;

impl ImageFormat {
    pub fn to_metal(self) -> metal::MTLPixelFormat {
        match self {
            ImageFormat::BC1_RGBA_SRGB_BLOCK => metal::MTLPixelFormat::BC1_RGBA_sRGB,
            ImageFormat::BC1_RGBA_UNORM_BLOCK => metal::MTLPixelFormat::BC1_RGBA,
            ImageFormat::BC2_SRGB_BLOCK => metal::MTLPixelFormat::BC2_RGBA_sRGB,
            ImageFormat::BC2_UNORM_BLOCK => metal::MTLPixelFormat::BC2_RGBA,
            ImageFormat::BC3_SRGB_BLOCK => metal::MTLPixelFormat::BC3_RGBA_sRGB,
            ImageFormat::BC3_UNORM_BLOCK => metal::MTLPixelFormat::BC3_RGBA,
            ImageFormat::BC4_SNORM_BLOCK => metal::MTLPixelFormat::BC4_RSnorm,
            ImageFormat::BC4_UNORM_BLOCK => metal::MTLPixelFormat::BC4_RUnorm,
            ImageFormat::BC5_SNORM_BLOCK => metal::MTLPixelFormat::BC5_RGSnorm,
            ImageFormat::BC5_UNORM_BLOCK => metal::MTLPixelFormat::BC5_RGUnorm,
            ImageFormat::BC6H_SFLOAT_BLOCK => metal::MTLPixelFormat::BC6H_RGBFloat,
            ImageFormat::BC6H_UFLOAT_BLOCK => metal::MTLPixelFormat::BC6H_RGBUfloat,
            ImageFormat::BC7_SRGB_BLOCK => metal::MTLPixelFormat::BC7_RGBAUnorm_sRGB,
            ImageFormat::BC7_UNORM_BLOCK => metal::MTLPixelFormat::BC7_RGBAUnorm,
            ImageFormat::D16_UNORM => metal::MTLPixelFormat::Depth16Unorm,
            ImageFormat::D24_UNORM_S8_UINT => metal::MTLPixelFormat::Depth24Unorm_Stencil8,
            ImageFormat::D32_SFLOAT => metal::MTLPixelFormat::Depth32Float,
            ImageFormat::D32_SFLOAT_S8_UINT => metal::MTLPixelFormat::Depth32Float_Stencil8,
            ImageFormat::R16_SFLOAT => metal::MTLPixelFormat::R16Float,
            ImageFormat::R16_SINT => metal::MTLPixelFormat::R16Sint,
            ImageFormat::R16_SNORM => metal::MTLPixelFormat::R16Snorm,
            ImageFormat::R16_UINT => metal::MTLPixelFormat::R16Uint,
            ImageFormat::R16_UNORM => metal::MTLPixelFormat::R16Unorm,
            ImageFormat::R16G16_SFLOAT => metal::MTLPixelFormat::RG16Float,
            ImageFormat::R16G16_SINT => metal::MTLPixelFormat::RG16Sint,
            ImageFormat::R16G16_SNORM => metal::MTLPixelFormat::RG16Snorm,
            ImageFormat::R16G16_UINT => metal::MTLPixelFormat::RG16Uint,
            ImageFormat::R16G16_UNORM => metal::MTLPixelFormat::RG16Unorm,
            ImageFormat::R16G16B16A16_SFLOAT => metal::MTLPixelFormat::RGBA16Float,
            ImageFormat::R16G16B16A16_SINT => metal::MTLPixelFormat::RGBA16Sint,
            ImageFormat::R16G16B16A16_SNORM => metal::MTLPixelFormat::RGBA16Snorm,
            ImageFormat::R16G16B16A16_UINT => metal::MTLPixelFormat::RGBA16Uint,
            ImageFormat::R16G16B16A16_UNORM => metal::MTLPixelFormat::RGBA16Unorm,
            ImageFormat::R32_SFLOAT => metal::MTLPixelFormat::R32Float,
            ImageFormat::R32_SINT => metal::MTLPixelFormat::R32Sint,
            ImageFormat::R32_UINT => metal::MTLPixelFormat::R32Uint,
            ImageFormat::R32G32_SFLOAT => metal::MTLPixelFormat::RG32Float,
            ImageFormat::R32G32_SINT => metal::MTLPixelFormat::RG32Sint,
            ImageFormat::R32G32_UINT => metal::MTLPixelFormat::RG32Uint,
            ImageFormat::R32G32B32A32_SFLOAT => metal::MTLPixelFormat::RGBA32Float,
            ImageFormat::R32G32B32A32_SINT => metal::MTLPixelFormat::RGBA32Sint,
            ImageFormat::R32G32B32A32_UINT => metal::MTLPixelFormat::RGBA32Uint,
            ImageFormat::R8_SINT => metal::MTLPixelFormat::R8Sint,
            ImageFormat::R8_SNORM => metal::MTLPixelFormat::R8Snorm,
            ImageFormat::R8_SRGB => metal::MTLPixelFormat::R8Unorm_sRGB,
            ImageFormat::R8_UINT => metal::MTLPixelFormat::R8Uint,
            ImageFormat::R8_UNORM => metal::MTLPixelFormat::R8Unorm,
            ImageFormat::R8G8_SINT => metal::MTLPixelFormat::RG8Sint,
            ImageFormat::R8G8_SNORM => metal::MTLPixelFormat::RG8Snorm,
            ImageFormat::R8G8_SRGB => metal::MTLPixelFormat::RG8Unorm_sRGB,
            ImageFormat::R8G8_UINT => metal::MTLPixelFormat::RG8Uint,
            ImageFormat::R8G8_UNORM => metal::MTLPixelFormat::RG8Unorm,
            ImageFormat::R8G8B8A8_SINT => metal::MTLPixelFormat::RGBA8Sint,
            ImageFormat::R8G8B8A8_SNORM => metal::MTLPixelFormat::RGBA8Snorm,
            ImageFormat::R8G8B8A8_SRGB => metal::MTLPixelFormat::RGBA8Unorm_sRGB,
            ImageFormat::R8G8B8A8_UINT => metal::MTLPixelFormat::RGBA8Uint,
            ImageFormat::R8G8B8A8_UNORM => metal::MTLPixelFormat::RGBA8Unorm,
            ImageFormat::R10G10B10A2_UNORM => metal::MTLPixelFormat::RGB10A2Unorm,
            ImageFormat::R11G11B10_UFLOAT => metal::MTLPixelFormat::RG11B10Float,
        }
    }
}
