// Automatically generated by build.rs from src/vulkan/raytrace_structures.rs
// This file will be automatically re-generated by cargo

#ifndef _RAYTRACE_STRUCTURES_GLSL_
#define _RAYTRACE_STRUCTURES_GLSL_
#include "spectrum.glsl"

#define PT_STEPS 6

struct RTFrameData
{
  uint seed;
  uint lights_no;
  vec2 pixel_offset;
  float scene_radius;
  float exposure;
  vec2 scene_size;
  vec4 scene_centre;
};

struct RTInstance
{
  uint index_offset;
  uint index_count;
  uint material_id;
  uint transform_id;
};

struct RTMaterial
{
  vec4 diffuse_mul;
  vec4 emissive_col;
  Spectrum metal_ior;
  Spectrum metal_fresnel;
  uint diffuse;
  uint roughness;
  uint metalness;
  uint opacity;
  uint normal;
  uint bsdf_index;
  float roughness_mul;
  float metalness_mul;
  float anisotropy;
  float ior_dielectric;
  uint is_specular;
  uint is_emissive;
};

struct RTLight
{
  Spectrum color;
  vec4 pos;
  vec4 dir;
  uint shader;
  uint instance_id;
  float intensity;
  bool delta;
};

struct PTLastVertex
{
  Spectrum importance;
  vec4 wi;
  vec4 hit;
};

#endif

