[package]
name = "glaze-converter"
version = "0.3.0"
authors = ["Davide Pizzolotto <davide.pizzolotto@gmail.com>"]
license = "MIT"
edition = "2018"

[[bin]]
name = "glaze-converter"
path = "src/main.rs"

[dependencies]
glaze = {path = "../lib", default-features=false}
clap = "2.33"
cgmath = "0.18"
russimp = "1.0.1"
indicatif = "0.16"
console = "0.15"
image = "0.23"
rayon = "1.5"

[dev-dependencies]
tempfile = "3.2"
